### ISSUE TITLE
手势指令怎么传参数呀？

### ISSUE THREAD

**Issue by cindygogogo** [daughterRui/vue-finger-directive#1]
<div v-pressMove="{methods: pressMove, args: 'args' }" style="width:100%; height: 50px;background-color:blue;">press</div>

 pressMove (e, args) {
      console.log(args)
    },
 div是列表循环的，想把index传到pressMove里面

**Comment by daughterRui** [comment]
<div
  :style="floatStyle"
  class="floating"
  v-pressMove="{methods: pressMove }"
  ref="floating"
  v-tap="{methods: tap, arg: {index: 1, item:{name: "name", value: "value"}} }"
>
methods: {
  pressMove(){
    
  },
  tap(e, arg){
    console.log('arg', arg)
  }
}

**Comment by daughterRui** [comment]
<div
  :style="floatStyle"
  class="floating"
  v-pressMove="{methods: pressMove }"
  ref="floating"
  v-tap="{methods: tap, arg: {index: 1, item:{name: "name", value: "value"}} }"
>
methods: {
  pressMove(){
    
  },
  tap(e, arg){
    console.log('arg', arg)
  }
}

**Comment by daughterRui** [comment]
请看更新的readme文档
